{% set version = "3.0.0.rc1" %}
{% set rel_version = "3.0.0-rc1" %}

package:
  name: mpir
  version: {{ version }}

source:
  fn: mpir-{{ version }}.tar.bz2
  url: http://mpir.org/mpir-{{ rel_version }}.tar.bz2
  sha256: 90c3dabda2ee9100857dd73752e7a24b51adebee3821d39e7481451dea7f7370

build:
  number: 0
  skip: true          # [not py35]
  features:
    - vc14            # [win and py35]

requirements:
  build:
    - m4              # [unix]
    - python
    - toolchain       # [unix]
    - yasm            # [unix]
    - vc 14           # [win and py35]
  run:
    - vc 14           # [win and py35]

test:
  files:
    - test.c
  commands:
    - if not exist %LIBRARY_INC%\\mpir.h exit 1                # [win]
    - if not exist %LIBRARY_INC%\\mpirxx.h exit 1              # [win]
    - if not exist %LIBRARY_INC%\\gmp.h exit 1                 # [win]
    - if not exist %LIBRARY_INC%\\gmpxx.h exit 1               # [win]

    - if not exist %LIBRARY_LIB%\\mpir.lib exit 1              # [win]
    - if not exist %LIBRARY_LIB%\\gmp.lib exit 1               # [win]
    - if not exist %LIBRARY_BIN%\\mpir.dll exit 1              # [win]
    - if not exist %LIBRARY_BIN%\\gmp.dll exit 1               # [win]

    - if not exist %LIBRARY_LIB%\\mpir_static.lib exit 1       # [win]
    - if not exist %LIBRARY_LIB%\\mpirxx_static.lib exit 1     # [win]
    - if not exist %LIBRARY_LIB%\\gmp_static.lib exit 1        # [win]
    - if not exist %LIBRARY_LIB%\\gmpxx_static.lib exit 1      # [win]

    - test -f $PREFIX/include/mpir.h                           # [unix]
    - test -f $PREFIX/include/mpirxx.h                         # [unix]
    - test -f $PREFIX/lib/libmpir.a                            # [unix]
    - test -f $PREFIX/lib/libmpirxx.a                          # [unix]

    - test -f $PREFIX/lib/libmpir.so                           # [linux]
    - test -f $PREFIX/lib/libmpirxx.so                         # [linux]

    - test -f $PREFIX/lib/libmpir.dylib                        # [osx]
    - test -f $PREFIX/lib/libmpirxx.dylib                      # [osx]

about:
  home: http://mpir.org/
  license: LGPL 3
  license_file: COPYING.LIB
  summary: Multiple Precision Integers and Rationals.

extra:
  recipe-maintainers:
    - isuruf
    - jakirkham
