{% set version = "3.0.1.dev0" %}

package:
  name: mpir
  version: {{ version }}

source:
  url: https://github.com/BrianGladman/mpir/archive/master.tar.gz

build:
  number: 0
  skip: true          # [win and vc<14]
  run_exports:
    - {{ pin_subpackage("mpir") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m4              # [unix]
    - python
    - yasm            # [unix]
    - autoconf        # [unix]
    - libtool         # [unix]
    - make            # [unix]
  host:
  run:

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  files:
    - test.c
  commands:
    - if not exist %LIBRARY_INC%\\mpir.h exit 1                # [win]
    - if not exist %LIBRARY_INC%\\mpirxx.h exit 1              # [win]
    - if not exist %LIBRARY_INC%\\gmp.h exit 1                 # [win]
    - if not exist %LIBRARY_INC%\\gmpxx.h exit 1               # [win]

    - if not exist %LIBRARY_LIB%\\mpir.lib exit 1              # [win]
    - if not exist %LIBRARY_LIB%\\gmp.lib exit 1               # [win]
    - if not exist %LIBRARY_BIN%\\mpir.dll exit 1              # [win]
    - if not exist %LIBRARY_BIN%\\gmp.dll exit 1               # [win]

    - if not exist %LIBRARY_LIB%\\mpir_static.lib exit 1       # [win]
    - if not exist %LIBRARY_LIB%\\mpirxx_static.lib exit 1     # [win]
    - if not exist %LIBRARY_LIB%\\gmp_static.lib exit 1        # [win]
    - if not exist %LIBRARY_LIB%\\gmpxx_static.lib exit 1      # [win]

    - test -f $PREFIX/include/mpir.h                           # [unix]
    - test -f $PREFIX/include/mpirxx.h                         # [unix]
    - test -f $PREFIX/lib/libmpir.a                            # [unix]
    - test -f $PREFIX/lib/libmpirxx.a                          # [unix]

    - test -f $PREFIX/lib/libmpir.so                           # [linux]
    - test -f $PREFIX/lib/libmpirxx.so                         # [linux]

    - test -f $PREFIX/lib/libmpir.dylib                        # [osx]
    - test -f $PREFIX/lib/libmpirxx.dylib                      # [osx]

about:
  home: http://mpir.org/
  license: LGPL 3
  license_file: COPYING.LIB
  summary: Multiple Precision Integers and Rationals.

extra:
  recipe-maintainers:
    - isuruf
    - jakirkham
