appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: bLOWutV/E1EUoRYL/0B03X27HpP7amUOtmVr8JTU0Tb+NdVWN6wcZEOkv7K8AV6sJYSk2MOlKt+K2Str1rFUnGdNVERwSvGk5Md1ecr8hNyHMc9s+Z29dL4uYatocKjAxKgTGFiu14IyOCrx2GQwNh0WeOqIxbW2nsJ8SwtUz+qmeS4+Aj9y76g6jkSUyjFA4TxbhIWLJQhsujSmI1vgIDFrIDYvarzhSbJB4wnbeB+lmIqguRe2d+phNbKOdLEeYh0R+l1YdzIOs4eOPdOp0QMAXAzuCqCDFChtwxZZIjIhnd+uHBXLAiN0zwHWMUiTxsGMsBP/zpoSSYA/z+cSlJI+kxn/29aJKkV6yaTGn8zvEiuUlKtrdQa6bUaCMmlC5Earp5Wx0b1btCq8dB07a5JuQFdzO5uBXrmZc9sjTrvrdxjRZZo9s1nynSAcDBbBMALz9bASi775haNvdLmszWcjGq5ikiP+WUhPiGhK9YwcWlnhDZTNg0l9yBF4XW3FOpL7k8BxlxAbgsEXkmyAO9MS2bihtVdhu52RpfCk2fc171q6yOVjloGbEPWfk6+mps7Xdk8wY8s2i5A+tRifs56WoY5S6yNdMqfLCFoopNLZR0Sivp16DZ248UIZ6ElNQLyzTD3+4uLlaOOlYK3bppWdR4YOnFCoXDGPbBlSvRc=}
